version: "3.8"

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: margdarshak_backend
    restart: unless-stopped
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://margdarshak:margdarshak123@postgres:5432/margdarshak_db
      - REDIS_URL=redis://redis:6379/0
      - JWT_SECRET=margdarshak_prod_jwt_secret_key_2026
      - ENVIRONMENT=production
      - DEBUG=False
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_started
    volumes:
      - .:/app

  postgres:
    image: postgis/postgis:16-3.4
    container_name: margdarshak_postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: margdarshak
      POSTGRES_PASSWORD: margdarshak123
      POSTGRES_DB: margdarshak_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U margdarshak -d margdarshak_db"]
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    container_name: margdarshak_redis
    restart: unless-stopped
    ports:
      - "6379:6379"

volumes:
  postgres_data:
